package org.scadalts.e2e.common.core.types;

public enum TestPlan {
    SERVICE, PAGE, CHECK, PAGE_SERVICE, SERVICE_PAGE, ALL, ANY, LOGIN, LOGOUT,
    AUTO_CONFIG, CONFIG_AUTO, EXPORT, IMPORT, CLEAN, PERFORMANCE, PERF,
    ALARM_NOTIFICATION_AUTO_CONFIG, PROD, FROM_GROOVY_SCRIPT, ALARM_STORUNG, CONFIG_PROD_CHECKER,
    GEN_BACKSTOP_CONFIG
}
